### ISSUE TITLE
Expired SSL Certificate

### ISSUE THREAD

**Issue by steverobbins** [YoSmudge/dnsyo#23]
The certificate for https://www.codesam.co.uk/ has expired

![Image](https://i.imgur.com/qJSdmM1.png)

Causing this error:

```
INFO:root:Updating resolver list file
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.codesam.co.uk
Traceback (most recent call last):
  File "/usr/local/bin/dnsyo", line 9, in <module>
    load_entry_point('dnsyo==2.0.9', 'console_scripts', 'dnsyo')()
  File "build/bdist.macosx-10.11-x86_64/egg/dnsyo/cli.py", line 160, in run
  File "build/bdist.macosx-10.11-x86_64/egg/dnsyo/dnsyo.py", line 146, in updateList
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```

**Comment by YoSmudge** [comment]
Hi, Sorry about that. Fixed now

**Comment by danielitus** [comment]
It could be that the certificate is expired?
 Certificate Expiration       expired! (2016-06-21 08:17 --> 2016-09-19 08:17 -0300)
